spring:
  application:
    name: ai-code-helper
server:
  port: 8081
  servlet:
      context-path: /api


langchain4j:
  community:
    dashscope:
      chat-model:
        model-name: qwen-plus
        api-key: ${API-KEY}
      embedding-model:
        model-name: text-embedding-v4
        api-key: ${API-KEY}
      streaming-chat-model:
        model-name: qwen-plus
        api-key: ${API-KEY}
bigmodel:
  api-key: 9915ca91ed294603a817564f4bd54c4d.YR6v8D4fXkWFLKhM